### ISSUE TITLE
There is no bind()

### ISSUE THREAD

**Issue by SlightlyCyborg** [usocket/usocket#41]
How do I create a UDP server without bind?

**Comment by SlightlyCyborg** [comment]
Ok. So I see bind in `socket-connect`, but only if `:local-host` or `:local-port` is provided. The API here is really screwy, because the only way bind is performed is if `host` and `port` are set to `nil` (on sbcl). This is not in the documentation. Also, on CCL, if I don't set both `:local-host` and `:local-port` then the socket won't bind properly. 

`socket-bind` and `socket-connect` should be separated desu.

**Comment by hanshuebner** [comment]
usocket is not specific to the BSD socket API.  If you need access to the
socket API, consider https://github.com/sionescu/iolib

>

**Comment by binghe** [comment]
Hi @SlightlyCyborg,

if you call `socket-connect` with non-empty `:local-host` and `:local-port`, and empty `host` and `port`, then `socket-connect` will do nothing but a `bind` for you.  But then you can't connect to specific host/port any more, instead, when you call `socket-send` and `socket-receive` you must provide the destination host and port explicitly, however there's no difference from the view of actual data transmission.

We didn't provide `socket-bind` because we want to minimized the number of API functions. Usually when people create a UDP socket bound to a local host/port, such a socket is usually for creating UDP servers which serve more then one clients, then there's no need to further connect it to a single specific client host/port.

If you really need a full feature, just use platform-specific socket API, or IOlib as @hanshuebner has pointed out.

Hope this helps,

Chun
