### ISSUE TITLE
usocket leaks file descriptors on sb-int:broken-pipe conditions

### ISSUE THREAD

**Issue by jesseoff** [usocket/usocket#64]
In the following code:

```lisp
        (bt:make-thread
         (lambda ()
           (log-errors (bt:with-timeout (15)
                         (with-client-socket (sk s remote 19023 :element-type '(unsigned-byte 8))
                           (write-sequence resp s)))))
```

When write-sequence is a big long write that has its connection reset midway, the unwind-protect in with-client-socket does not seem to close the FD and I eventually run out of fds.  There is a sb-int:broken-pipe condition sent that seems to be throw from within the stream close.  

Trace output (never returns normally so there is no trace prints for return values.
```
  0: (USOCKET:SOCKET-CLOSE #<USOCKET:STREAM-USOCKET {1002D486A3}>)
    1: (CLOSE #<SB-SYS:FD-STREAM for "socket 192.168.2.1:54255, peer: 192.168.2.2:19023" {1002D497A3}>)
```

**Comment by jesseoff** [comment]
Pretty sure whats happening is that theres a signal in the write-sequence because the remote closed the pipe, and then again in the stream socket close unwind-protect cleanup form for the same reason (closes can fail too).  With a failed close call in the unwind protect, a fd is leaked forever.  I'm not even sure its failing in the close OS call, because the stream still has unwritten data and usocket prefers using the generic stream close, which likely takes another useless attempt at writing the streams unsent data again. (?)

**Comment by binghe** [comment]
Hi Jesse,

thanks for your analysis.  I think this issue is not only specific to SBCL but is general to all backends: when `SOCKET-CLOSE` on a stream usocket failed, sometimes the backends do not clean up the underlying socket fd. The obvious solution is to make sure the underlying socket fd is closed (by calling the right `SOCKET-CLOSE` method on it) when anything bad happens with `SOCKET-CLOSE` (for steam usockets).

I think the following code (in `usocket.lisp`) may work:

```
(in-package :usocket)

(defmethod socket-close :around ((usocket stream-usocket))
  (unwind-protect
      (call-next-method)
    (when (socket usocket)
      ;; make sure the (general) socket-close method is called
      (setq usocket (change-class usocket 'usocket))
      (socket-close usocket))))
```

That is, when `SOCKET-CLOSE` is called on a stream usocket, it first call the related method provided by backends (e.g. SBCL). Then, if anything goes wrong, and the current backend indeed allows the access of the underlying socket fd (SBCL is definitely included), then I change the class of the current usocket instance to the (general) `usocket` class and call `SOCKET-CLOSE` on it again. For SBCL, this means `(sb-bsd-sockets:socket-close (socket usocket))` instead of `(close (socket-stream usocket))`.

Could you please add the above code as a patch (i.e. a separate lisp file, but compiled and loaded) into your Lisp program and see if it resolves your problem?

Regards,

Chun

**Comment by jesseoff** [comment]
This still leaks fds for me.

Calling the usocket close after the stream-usocket close seems to make sense, however, for sbcl at least (maybe others?) the sb-bsd-sockets:socket-close method used in the generic usocket sbcl backend close notices its got a stream paired to it and calls the generic stream close anyway right there within sb-bsd-sockets:socket-close.  (check out https://github.com/sbcl/sbcl/blob/master/contrib/sb-bsd-sockets/sockets.lisp#L262 )

As expected, the generic stream close attempts to write some more, gets another exception thrown, and nothing really gets closed again.

I notice the stream close takes an :abort keyword arg, that is in the args of the sb-bsd-sockets:socket-close too.   Maybe that would avoid the exception-causing writes?

**Comment by jesseoff** [comment]
FWIW, I did just test adding an :abort t to the sbcl backend method for socket-close on usockets and it did fix the leak!

**Comment by binghe** [comment]
> FWIW, I did just test adding an :abort t to the sbcl backend method for socket-close on usockets and it did fix the leak!

That's great! I will add `:abort t` for all backends where they use `CL:CLOSE` on stream sockets. Thanks for your help on improving usocket.

**Comment by jesseoff** [comment]
Unrelated to this particular bug, but I might also suggest adding a `(sb-int:broken-pipe . connection-aborted-error)` to the `+sbcl-error-map+` I found my code unprepared in expecting that particular condition sbcl was signaling.

**Comment by binghe** [comment]
> Unrelated to this particular bug, but I might also suggest adding a `(sb-int:broken-pipe . connection-aborted-error)` to the `+sbcl-error-map+` I found my code unprepared in expecting that particular condition sbcl was signaling.

This makes sense. Thanks again!
